name: Deploy Site
on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["*"]

concurrency:
  group: site-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
    
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        run: flyctl deploy
        if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
