name: Index
on:
  schedule:
    - cron: "0 2 * * 1,3,5,0"
  workflow_dispatch:

env:
  JAVA_OPTS: "-Xmx4G"
  JVM_OPTS: "-Xmx4G"
  SBT_OPTS: "-Xmx4G"

jobs:
  build:
    name: Index repos
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      SCALABOOT_API_KEY: ${{ secrets.SCALABOOT_API_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "sbt"

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg
          key: ${{ runner.os }}-sbt-vcpkg

      - uses: sbt/setup-sbt@v1

      - name: HACK publish Tapir
        run: cd .tapir && sbt "coreNative3/publishLocal; circeJsonNative3/publishLocal; clientCoreNative3/publishLocal; sttpClient4Native3/publishLocal"

      - run: sbt buildRepoIndexerRelease

      - run: |
          set -eu

          cat .github/workflows/fixtures/orgs-to-index.txt | \
            parallel -j 1 ./out/release/repo-indexer --org {}
