name: Index
on: 
  schedule:
  - cron: "0 2 * * 1,3,5,0"
  workflow_dispatch:

env: 
  JAVA_OPTS: "-Xmx4G"
  JVM_OPTS: "-Xmx4G"
  SBT_OPTS: "-Xmx4G"

jobs:
  build:
    name: Index repos
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      SCALANATIVE_MODE: release-fast
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'sbt'

      - run: sbt buildRepoIndexer

      - run: |
          ./build/scala-boot-repo-indexer --org http4s
          ./build/scala-boot-repo-indexer --org typelevel

