name: Index
on: 
  schedule:
  - cron: "0 2 * * 1,3,5,0"
  workflow_dispatch:

env: 
  JAVA_OPTS: "-Xmx4G"
  JVM_OPTS: "-Xmx4G"
  SBT_OPTS: "-Xmx4G"

jobs:
  build:
    name: Index repos
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      SCALANATIVE_MODE: release-fast
      SCALANATIVE_LTO: thin
      SCALABOOT_API_KEY: ${{ secrets.SCALABOOT_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'sbt'

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg
          key: ${{ runner.os }}-sbt-vcpkg

      - run: sbt buildRepoIndexer

      - run: |
          set -eu

          cat .github/workflows/fixtures/orgs-to-index.txt | \
            parallel -j 1 ./build/scala-boot-repo-indexer --org {}

